# Project Name
TARGET = tri_chorus

# Sources and Hothouse header files
CPP_SOURCES = tri_chorus.cpp ../hothouse.cpp
C_INCLUDES = -I..

# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
