# Project Name
TARGET = harmonic_trem_verb

USE_DAISYSP_LGPL=1

# Sources and Hothouse header files
CPP_SOURCES = harmonic_trem_verb.cpp extended_oscillator.cpp ../hothouse.cpp
C_INCLUDES = -I..

# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
